"use strict";Object.defineProperty(exports,"__esModule",{value:true});exports.getDepsExact=getDepsExact;exports.getDeps=getDeps;exports.normalise=normalise;exports.transform=transform;exports.transformDependency=exports.isExact=exports.getPeerDependencies=exports.getBundleDependencies=exports.getOptionalDependencies=exports.getDevDependencies=exports.getProdDependencies=exports.getCommands=exports.getNoSaveParam=exports.getSaveExactParam=exports.getRegistryParam=exports.NVM=exports.REGISTRY=exports.DIRECTORY=void 0;var _debug=_interopRequireDefault(require("debug"));var _path=require("path");function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj};}const log=(0,_debug.default)('@modernpoacher/deps');log('`common` is awake');const{path:MODULE_PATH}=module;const DIRECTORY='.';exports.DIRECTORY=DIRECTORY;const REGISTRY='https://registry.npmjs.org';exports.REGISTRY=REGISTRY;const NVM=(0,_path.resolve)(MODULE_PATH,'../../nvm.sh');exports.NVM=NVM;const getRegistryParam=(r,v)=>r?v.concat(` --registry ${r}`):v;exports.getRegistryParam=getRegistryParam;const getSaveExactParam=(e,v)=>e?v.concat(' --save-exact'):v;exports.getSaveExactParam=getSaveExactParam;const getNoSaveParam=(s,v)=>s?v:v.concat(' --no-save');exports.getNoSaveParam=getNoSaveParam;const getCommands=(directory=DIRECTORY,commands='npm i')=>`
export PATH=/usr/local/bin:$PATH &> /dev/null

cd "${directory}"

. "${NVM}"

${commands}

exit 0
`.replace(/\n\n/gm,String.fromCharCode(10)).trim();exports.getCommands=getCommands;const getProdDependencies=({dependencies={}}={})=>dependencies;exports.getProdDependencies=getProdDependencies;const getDevDependencies=({devDependencies={}}={})=>devDependencies;exports.getDevDependencies=getDevDependencies;const getOptionalDependencies=({optionalDependencies={}}={})=>optionalDependencies;exports.getOptionalDependencies=getOptionalDependencies;const getBundleDependencies=({bundleDependencies=[]}={})=>bundleDependencies;exports.getBundleDependencies=getBundleDependencies;const getPeerDependencies=({peerDependencies}={})=>peerDependencies;exports.getPeerDependencies=getPeerDependencies;const isExact=v=>/^\d/.test(v);exports.isExact=isExact;function getDepsExact(values,configuration){log('getDepsExact');return Object.entries(values).reduce((accumulator,[name,version])=>isExact(version)?accumulator.concat({name,version:Reflect.has(configuration,name)?Reflect.get(configuration,name):version}):accumulator,[]);}function getDeps(values){log('getDeps');return Object.entries(values).reduce((accumulator,[name,version])=>isExact(version)?accumulator:accumulator.concat({name,version:'latest'}),[]);}function normalise(value){while(/\s\s|\n/.test(value)){value=value.replace(/\s\s/gm,String.fromCharCode(32)).replace(/\n/gm,String.fromCharCode(32));}return value.trim();}const transformDependency=({name='@modernpoacher/deps',version='latest'}={})=>`${name}@${version}`;exports.transformDependency=transformDependency;function transform(value){log('transform');return Array.isArray(value)?value.map(transformDependency).join(String.fromCharCode(32)).trim():transformDependency(value);}